language: node_js
node_js: "12"
sudo: required

services:
  - docker

branches:
  only:
    - master
    - development

before_script:
  - npm install -g @angular/cli
  - export DISPLAY=:99.0
  - sudo systemctl start xvfb

script:
  - cd frontend
  - npm install
  - ng build --prod
  #- ng test --browsers Firefox
  - cd ..
  - cd readonly
  - npm install
  - ng build --prod
  #- ng test --browsers Firefox
  - cd ..
  - cd login
  - npm install
  - ng build --prod
  #- ng test --browsers Firefox
  - cd ..
  - cd backend
  - npm install
  - cd ..
  - docker-compose -f docker-compose-test.yml up --exit-code-from backend

cache:
  directories:
    - frontend/node_modules
    - readonly/node_modules
    - login/node_modules
    - backend/node_modules
