FROM node:12.10.0-alpine
ENV HOME=/usr/src/app
RUN mkdir -p $HOME
WORKDIR $HOME
COPY entrypoint.sh /usr/src/
RUN chmod +x /usr/src/entrypoint.sh
USER 1000
ENTRYPOINT ["/usr/src/entrypoint.sh"]
CMD ["run", "start"]