FROM node:16.13.2-alpine
ENV HOME=/usr/src/app
RUN mkdir -p $HOME
WORKDIR $HOME
COPY entrypoint.sh /usr/src/
RUN chmod +x /usr/src/entrypoint.sh
ENTRYPOINT ["/usr/src/entrypoint.sh"]
CMD ["run", "start"]
